version: '3.7'
services:
  pgdb:
    image: postgres:16.2-alpine3.19
    container_name: pgdb
    ports:
      - "8888:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  pgdata:
    driver: local
